[versions]
minecraft = "26.3"
fabric-loader = "0.19.5"
fabric-api = "0.160.6+26.3"
fabric-loom = "1.17-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-loom-plugin = { module = "net.fabricmc.fabric-loom:net.fabricmc.fabric-loom.gradle.plugin", version.ref = "fabric-loom" }
foojay-resolver-convention-plugin = { module = "org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin", version = "1.0.0" }
modmenu = { module = "com.terraformersmc:modmenu", version = "21.0.0-beta.1" }

# Versions of the Fabric API modules below are managed by the BOM.
fabric-api-bom = { module = "net.fabricmc.fabric-api:fabric-api-bom", version.ref = "fabric-api" }
fabric-api-base = { module = "net.fabricmc.fabric-api:fabric-api-base" }
fabric-resource-loader-v0 = { module = "net.fabricmc.fabric-api:fabric-resource-loader-v0" }
fabric-screen-api-v1 = { module = "net.fabricmc.fabric-api:fabric-screen-api-v1" }
fabric-lifecycle-events-v1 = { module = "net.fabricmc.fabric-api:fabric-lifecycle-events-v1" }
